### ISSUE TITLE
User is requested to accept the Firefox Add-ons Agreement every time his account is updated

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#1096]
Steps to reproduce:
1. Sign to AMO stage page https://addons.allizom.org/en-US/firefox/ with an already used account
2. Make some changes to your account (i.e or just hit "Update Account" button from Account Settings)
3. Click the "Submit a New Add-on" option from Tools

Expected results:
Step #2 page of submission process is loaded.

Actual results:
User is asked to accept the Firefox Add-ons Agreement again.

Notes/Issues:
Verified on FF43(Win 7). Issue is reproducing on AMO-stage, AMO-dev and AMO-prod.
Screencast for this issue: http://screencast.com/t/gqpB3OGTZ9

**Comment by andymckay** [comment]
Sounds like each change to the profile is wiping out the profile accepted field. Should be a pretty easy fix.

**Comment by LadyLovesCode** [comment]
Is anyone working on this? I've recently started contributing to Air Mozilla and I'm looking for another Mozilla project I can contribute to. Is this something I could work on?

**Comment by andymckay** [comment]
Please go for it.

**Comment by andymckay** [comment]
@LadyLovesCode are you working on this, otherwise @Nolski might.

**Comment by LadyLovesCode** [comment]
@andymckay I actually hadn't started yet, so that's okay. Go for it., @Nolski :)

**Comment by NalinG** [comment]
Is someone working on it.? Because I would like to as I just started contributing to Mozilla

**Comment by runejuhl** [comment]
Not really familiar with Django, but wouldn't changing `request.user.read_dev_agreement` to `request.user.accept_agreement` (in https://github.com/mozilla/addons-server/blob/be46dbe8ca6121e8dcab1dcbad9c6d60bddccc2c/src/olympia/devhub/views.py#L1422) fix this issue? The agreement form template is at https://github.com/mozilla/addons-server/blob/76f1143fc1409dbfed4f94f5bba2b6961c0efefd/src/olympia/devhub/templates/devhub/agreement.html

**Comment by mstriemer** [comment]
This was fixed during the FxA migration.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF45(Win 7).
This issue is still reproducing if we delete the account just from AMO (no need to delete it from FxA) and re-log using the same account.
Please see the screencast: http://screencast.com/t/jM6lPJf2KL
I guess this is this intended...  @mstriemer ?

**Comment by mstriemer** [comment]
If you delete and sign in with the same FxA it is creating a new account on AMO so this is working as intended.
