### ISSUE TITLE
500 error triggered when attempting to add to blocks a previously deleted block (signed-off)

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-server#13523]
### Describe the problem and steps to reproduce it:
1. Log in with an admin user
2. Open the admin blocklisting tool and add a new guid to blocks (make sure that your selection requires sign-off)
3. With another user that has `Blocklist:Signoff` rights, Approve the block submission
4. With the first user, open the block list view and delete the newly published block
5. Try to block the same guid again

### What happened?
You receive a 500 server error

### What did you expect to happen?
The block submission is successfully processed

### Anything else we should know?
- this issue doesn't occur when the add-on doesn't go through the dual sign-off process

**Comment by eviljeff** [comment]
can you still replicate this?  I can't locally - I think it will have been fixed at the same time as https://github.com/mozilla/addons-server/issues/13489

**Comment by AlexandraMoga** [comment]
@eviljeff I will see if I'm still reproducing after  addons-server deploys are fixed. Right now, the most recent code available on -dev is from last Wednesday

**Comment by AlexandraMoga** [comment]
I've re-verified this scenario on -dev and is no longer reproducible after the fix for #13489
