### ISSUE TITLE
Fix language packs pointing to `*` as their max AppVersion

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#14653]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1646016 we noticed some language packs versions are linked to a max `AppVersion` of `*`. This cause the langpacks to be returned for Firefox versions they don't correspond to.

We need to write a script to fix that data by querying langpacks that have versions that are linked to `*` in the database, extract relevant XPIs, and link to the correct max `AppVersion` instead.

**Comment by eviljeff** [comment]
we think (for langpacks) we can just use the relevant min version to match to the max version.  e.g. if the min_version was 69.0 we can assume the max_version was supposed to be 69.*

**Comment by diox** [comment]
Good idea, although I'm not sure if that makes it easier, since we need to find the right row in the database for each version

**Comment by diox** [comment]
QA: Bear with me as explaining this is a bit tricky. Once this command is ran, langpack versions with a max Firefox/Android version compatibility set to`*` will see that max version compatibility changed to  `<major>.*`, where `<major>` is the major version number of the min Firefox/Android version set.

It's better explaining with the following examples:
- If a langpack version has max compatibility set to `77.*`, no changes
- If a langpack version has max compatibility set to `*`, and their min compatibility is set to `77.0`, the max will change to `77.*`

Please prepare some langpacks in various states and let me know when I can fire the command to test.

**Comment by AlexandraMoga** [comment]
@diox I'm creating some samples now and will let you know when I'm ready

**Comment by AlexandraMoga** [comment]
@diox I think I have enough examples now. You can run the command on -dev.

**Comment by diox** [comment]
Done. I had to manually add a few missing appversions, including 99.*. (I've also deleted "Addon: 618365: Language Pack 99 to 99*" to test how the command behaved with that)

**Comment by AlexandraMoga** [comment]
Here are my test results:
1. for language pack with max compatibility set to `77.*` => there are no changes
2. for language pack with min compatibility set to `77.0` and max compatibility to `*` => max compatibility reset to `77.*`
3. for lang pack with min compatibility set to `79.0` and max compatibility to `*` => max compatibility reset to `79.*`
4. for lang pack with min compatibility set to `60.0a1` and max compatibility to `*` => max compatibility reset to `60.*`
5. for lang pack with min compatibility set to `70.0` and max compatibility to `99.*` => max compatibility reset to `70.*`

The command also ran on deleted and disabled versions (both user disabled and force disabled).
@diox it looks like the `max` compat version is being reset to the value of `min.*` version, as you mentioned in https://github.com/mozilla/addons-server/issues/14653#issuecomment-645331414
The results are looking correct to me.

**Comment by flodolo** [comment]
I see this is closed, but was this run on production? I'm still seeing answers to the API for `appVersion=99`, and I can still install language packs for 77 in Nightly.

**Comment by diox** [comment]
This hasn't been deployed and ran in production yet, but it will be today.
