### ISSUE TITLE
replace remaining links to devhub, with extensionworkshop equivalents

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-server#16753]
I think the links below are the remaining references to devhub that should go to extensionworkshop.com (though it wasn't 100% clear - sometimes we _do_ want to link to MDN, as that's where the technical documentation on the manifest structure is, for example). 

@caitmuenster can you confirm the new extensionworkshop.com link, including the UTM parm.

```
olympia • src\olympia\devhub\templates\devhub\includes\source_form_field.html:
  7:     <a href="https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews#Source_Code_Submission"
 
olympia • src\olympia\devhub\templates\devhub\new-landing\components\navigation.html:
  25:       <li class="in-hamburger-menu"><a href="https://developer.mozilla.org/en-US/Add-ons#Contact_us">
 
olympia • src\olympia\reviewers\templates\reviewers\emails\base.ltxt:
  11: You can also get in touch with us using these channels: https://developer.mozilla.org/Add-ons#Contact_us

  13: For tips on how to attract more users by updating your add-on’s listing, please visit: https://developer.mozilla.org/Add-ons/Listing

  15: To learn more about the review process, please visit: https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews

olympia • src\olympia\templates\copyright.html:
  18:         &nbsp;|&nbsp;<a href="https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact">{{ _('Report a bug')}}</a>

olympia • src\olympia\templates\photon-footer.html:
  15:                 <li><a href="https://developer.mozilla.org/docs/Mozilla/Add-ons/AMO/Policy">Developer Policies</a></li>

  17:                 <li><a class="Footer-bug-report-link" href="https://developer.mozilla.org/docs/Mozilla/Add-ons/Contact_us">Report a bug</a></li>
```

**Comment by eviljeff** [comment]
when someone implements this, there is a setting for the extensionworkshop.com url, so the templates should be written with `settings.EXTENSION_WORKSHOP_URL` rather than `https://extensionworkshop.com`

**Comment by eviljeff** [comment]
(fixed/added trailing `/` to extensionworkshop links above)

**Comment by kanish671** [comment]
I still see a few lingering links which are still pointing to the old URLs. I can fix these, and also convert all instances of `https://extensionworkshop.com` to `{{ settings.EXTENSION_WORKSHOP_URL }}`

**Comment by ioanarusiczki** [comment]
@eviljeff 
- for source code urls I filed https://github.com/mozilla/addons-server/issues/17181 because they open a 404 
- I don't know where should I find the urls from (what they refer to):
   `olympia • src\olympia\reviewers\templates\reviewers\emails\base.ltxt:

    "https://developer.mozilla.org/Add-ons/Listing" should be:
    ** text-only version: "https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/"
    ** HTML version: "https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/?utm_source=email&utm_medium=submission-email"

    "https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews" should be:
    ** text-only version: "https://extensionworkshop.com/documentation/publish/add-on-policies/"
    ** HTML version: "https://extensionworkshop.com/documentation/publish/add-on-policies/?utm_source=email&utm_medium=submission-email"

- the rest should be ok.

**Comment by kanish671** [comment]
I believe #17181  is caused by #17154 .
Specifically by changes in `src/olympia/devhub/templates/devhub/addons/submit/source.html`. 

I can look into fixing this. I think I misplaced the double quotes around `{{ settings.EXTENSION_WORKSHOP_URL }}`

**Comment by eviljeff** [comment]
>     * I don't know where should I find the urls from (what they refer to):
>       `olympia • src\olympia\reviewers\templates\reviewers\emails\base.ltxt:
>       "https://developer.mozilla.org/Add-ons/Listing" should be:
>       ** text-only version: "https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/"
>       ** HTML version: "https://extensionworkshop.com/documentation/develop/create-an-appealing-listing/?utm_source=email&utm_medium=submission-email"
>       "https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews" should be:
>       ** text-only version: "https://extensionworkshop.com/documentation/publish/add-on-policies/"
>       ** HTML version: "https://extensionworkshop.com/documentation/publish/add-on-policies/?utm_source=email&utm_medium=submission-email"

I think that was just @caitmuenster being thorough with the html/text variants - we don't have html emails for reviewer mails though so it'll just be the text-only links.

**Comment by eviljeff** [comment]
> I shall look into fixing this. I think I misplaced the double quotes around `{{ settings.EXTENSION_WORKSHOP_URL }}`

(discussion -> #17181 but) it's because the `{{ ... }}` tag has been added _inside_ another tag - the entire line is a `{% trans ...` tag so you can't do that.

**Comment by ioanarusiczki** [comment]
@eviljeff So checking fake e-mails on dev - for a listed addon version update I found those 2 and I filed an issue https://github.com/mozilla/addons-server/issues/17188.

**Comment by eviljeff** [comment]
As the PR caused two release blocking issues we've reverted the commit entirely.

**Comment by ioanarusiczki** [comment]
@eviljeff I checked on AMO stage - this has been reverted and right now the issues reported above are not reproducible.

**Comment by eviljeff** [comment]
I closed #17181 and #17188 but they serve as good references of what to avoid happening for he next PR.

**Comment by eviljeff** [comment]
@kanish671 from the experience here we don't think this is a good first bug.  

I'm going to deassign you from the issue as there isn't a PR open, but you're welcome to continue working on it if you want and open a new PR. You do need to setup addons-server locally and check the pages/emails are rendering correctly, really.  Templates in django are quite tolerant to errors - they'll just render white space rather than loudly complain if something if wrong so checking it manually is often the only way.

**Comment by eviljeff** [comment]
QA: there were only 2 links left to change in the end - the rest must have been picked up in other issues.
- the source code submission link in the upload flow (or the edit version page maybe?)
- the developer policies link in the footer in devhub (the landing page footer, I believe)

**Comment by AlexandraMoga** [comment]
The source code submission links from `/developers/addon/{addon}/submit/source` are now pointing to https://extensionworkshop.com/documentation/publish/source-code-submission/  - note that there are no `utm` parameters specified - filed #17723 

The Developer policies link for the DevHub landing page footer is  pointing to https://extensionworkshop-dev.allizom.org/documentation/publish/add-on-policies/?utm_source=addons.mozilla.org&utm_medium=photon-footer

The remaining links seem to be fine.

This issue is verified fixed on -dev.
