### ISSUE TITLE
Localized WebExtensions are displayed as __MSG_extensionName__

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-server#1681]
Localized extension names / descriptions were implemented in https://bugzilla.mozilla.org/show_bug.cgi?id=1192433.

But AMO doesn't support it. For example, if `manifest.json` contains `"name": "__MSG_extensionName__"`, and `_locales/en/messages.json` has defined `extensionName` as "test", then I would expect the displayed name to be "test", but AMO shows `__MSG_extensionName__`.

- The localization logic is here: https://hg.mozilla.org/mozilla-central/diff/eb7962bf88a8/toolkit/components/extensions/ExtensionUtils.jsm#l209
- Here is a sample extension: https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/test/addons/webextension_3
- An extension that was uploaded by a dev: https://addons.mozilla.org/en-US/editors/review/__msg_extensionname__ (only visible to reviewers, ask on `#amo-editors` if you need the xpi file).
- Documentation on the `__msg_XXXX_` syntax: https://developer.chrome.com/extensions/i18n

**Comment by kmaglione** [comment]
> Documentation on the __msg_XXXX_ syntax: https://developer.chrome.com/extensions/i18n

That's a generous description. You'd be better off reading the comments in ExtensionUtils.jsm.

**Comment by EnTeQuAk** [comment]
This is now fixed with the merge of https://github.com/mozilla/addons-server/pull/3012 - should be online on Thursday

**Comment by vcarciu** [comment]
I think that this issue is still reproducible, but now the name is "__MSG_extName__" . Please see the webextension for which I saw the issue


[Plus-for-Trello-(time-track,-reports,-scrum)_v4.1.4.zip](https://github.com/mozilla/addons-server/files/450093/Plus-for-Trello-.time-track.-reports.-scrum._v4.1.4.zip)

**Comment by vcarciu** [comment]
Also , please note that this type of webextension cannot be submitted to AMO because it says that the name is too long, even if during submission process I changed the name in order to meet the max length requirement : 
![webext](https://cloud.githubusercontent.com/assets/1583842/18173586/d846b7d6-7072-11e6-84d0-cb76b0a3a0a4.gif)

**Comment by EnTeQuAk** [comment]
The add-on you attached is invalid, it has an unneccessary sub-folder and doesn't directly contain all the neccessary files.

See my repackaged .zip attached which works fine for me.

[foo.zip](https://github.com/mozilla/addons-server/files/458772/foo.zip)

**Comment by vcarciu** [comment]
Verified as fixed
