### ISSUE TITLE
Load addons-server static files from /static-server on the main domain on dev

### ISSUE THREAD

**Issue by diox** [mozilla/addons-server#17988]
Essentially https://github.com/mozilla/addons-frontend/issues/10785 but for addons-server statics. We are currently loading addons-server statics on dev from https://addons-dev-cdn.allizom.org/static/, we want to load them from https://addons-dev.allizom.org/static-server/ (which is served from the CDN as the rest of the main domain) instead.

Once it's verified on dev we can enable it on stage & prod as well.

**Comment by AlexandraMoga** [comment]
@diox I'm seeing some errors in Reviewer and Admin tools related the the new `/static-server/`

Rev tools - font files:
![image](https://user-images.githubusercontent.com/31961530/135618504-0f739d6e-a91f-4e9c-9824-9309dbb043e9.png)


Admin tools - css and js files:
![image](https://user-images.githubusercontent.com/31961530/135618526-2145ea57-3fbe-4b76-98b7-fe2c7aaeb2e0.png)

**Comment by diox** [comment]
Ah thanks, I missed that.

**Comment by diox** [comment]
Ah thanks, I missed that.

**Comment by diox** [comment]
This should now be fixed, ops have adjusted CORS headers, fixing reviewer tools, and I ensured to always load the statics from the main domain even when on the admin site.

**Comment by AlexandraMoga** [comment]
@diox I'm still seeing CORS errors in rev tools and admin for font files. The pages are loading but the font is not the correct one.

**Comment by diox** [comment]
Mmm I'm not, so that's probably caching (on both the CDN side and your browser). I've cleared the CDN cache, could you clear your browser cache and try again ?

**Comment by AlexandraMoga** [comment]
Yes, looks good now.

**Comment by AlexandraMoga** [comment]
I'm not seeing any other issues on -dev related to the `/static-server/` transition.
