### ISSUE TITLE
Unlisted addon fails to pass validation with an unexpected error

### ISSUE THREAD

**Issue by mstewart20** [mozilla/addons-server#1885]
I've been able to use the automated validation/signing process to release my unlisted add-on until very recently. Whatever is in the most recent version of my addon breaks the validation process, I am unsure why.

Most recent version (named as .zip but it's my .xpi file from jpm): [firefox-at-getguru.com-1.1.24.2.zip](https://github.com/mozilla/addons-server/files/167247/firefox-at-getguru.com-1.1.24.2.zip)

The previous version (1.0.19.6) of the add on can be uploaded and revalidated just fine, so there is something different in the latest version that doesnt work at all.

Please attach a copy of your add-on, and fill in the following information:

* Whether this error occurred during the submission of a new add-on, a new version of an existing add-on, a new file in an existing version, or an upload to the standalone validator.

A new version of an exi

sting add-on

* Whether your add-on is listed or unlisted.

Unlisted

* The URL where you submitted the add-on.

https://addons.mozilla.org/en-US/developers/addon/guru/versions#version-upload

* The approximate time you submitted the add-on, with timezone.

March 9th, 2016 at 9:32pm, Eastern Standard Time

**Comment by jvillalobos** [comment]
Could be related to your massive CSS file, since we had a similar problem recently with [bug 1244644](https://bugzilla.mozilla.org/show_bug.cgi?id=1244644). @andymckay, is this a CSS-related error again?

**Comment by andymckay** [comment]
```
18:23:20 amo.validator:ERROR Unexpected error during validation: KeyError: 'line_number' :/usr/lib/python2.7/site-packages/validator/errorbundler.py:142
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/validator/submain.py", line 69, in prepare_package
    test_package(err, package, path, expectation, for_appversions)
  File "/usr/lib/python2.7/site-packages/validator/submain.py", line 165, in test_package
    test_inner_package(err, package, for_appversions)
  File "/usr/lib/python2.7/site-packages/validator/submain.py", line 375, in test_inner_package
    test_func(err, xpi_package)
  File "/usr/lib/python2.7/site-packages/validator/testcases/content.py", line 293, in test_packed_scripts
    testendpoint_js.test_js_file(err, script, file_data)
  File "/usr/lib/python2.7/site-packages/validator/testcases/scripting.py", line 26, in test_js_file
    tree = get_tree(data, filename=filename, err=err)
  File "/usr/lib/python2.7/site-packages/validator/testcases/javascript/jsshell.py", line 14, in get_tree
    return JSShell.get_shell().get_tree(code)
  File "/usr/lib/python2.7/site-packages/validator/testcases/javascript/jsshell.py", line 114, in get_tree
    output['line_number'])
KeyError: 'line_number'
```
Is the error I get, after a while. I've seen this before...

**Comment by andymckay** [comment]
mozilla/addons#41

**Comment by mstewart20** [comment]
Thanks @jvillalobos for pointing that out, looks like we had a bad build script that put source maps in the CSS. I've stripped that out and tried to validate again but still no luck.

We also have base64 encoded font files in the CSS as well, that's my next step but wanted to upload the latest xpi file to see if there was anything different.

[firefox-at-getguru.com-1.1.24.2.zip](https://github.com/mozilla/addons-server/files/167852/firefox-at-getguru.com-1.1.24.2.zip)

**Comment by mstewart20** [comment]
One more comment, the previous version also had a massive css file (complete with source maps and base64 fonts).

Here's the attached xpi

[firefox-at-getguru.com-1.0.19.6.zip](https://github.com/mozilla/addons-server/files/167866/firefox-at-getguru.com-1.0.19.6.zip)

**Comment by andymckay** [comment]
@EnTeQuAk and @mstriemer were looking at this and I think the error is masking something else, possibly a recursion error in one of the JSON files.

**Comment by mstewart20** [comment]
Hi there!

Is there a way to get my addon manually verified until this issue is resolved? Thank you!

**Comment by jvillalobos** [comment]
Can you confirm that the problem still happens?

**Comment by mstewart20** [comment]
Yes unfortunately this does still occur. I've tried with various latest versions and it still fails the validation with an unexpected error and a request to log a bug here.

**Comment by jvillalobos** [comment]
Please attach the latest version and I'll try to upload it for you.

**Comment by mstewart20** [comment]
Here's the latest.


[firefox@getguru.com-1.1.24.12.zip](https://github.com/mozilla/addons-server/files/192395/firefox.getguru.com-1.1.24.12.zip)

**Comment by jvillalobos** [comment]
Done, the new version is up and signed.

**Comment by mstewart20** [comment]
Thank you! I'll keep watching this issue and the associated ones for updates.

**Comment by mstewart20** [comment]
I was wondering what the next steps are? It looks like this issue didn't seem to resolve the problem: https://github.com/mozilla/addons-server/issues/1911

We do plan on releasing another version in the next week or two, should I just come back here and request another manual review?

**Comment by jvillalobos** [comment]
Yes, you can attach new versions here while this is resolved.

**Comment by mstewart20** [comment]
@jvillalobos Please find a new version of the extension here:

[firefox@getguru.com-1.2.1.19.zip](https://github.com/mozilla/addons-server/files/203810/firefox.getguru.com-1.2.1.19.zip)


Thank you for reviewing manually!

**Comment by jvillalobos** [comment]
Added.
