### ISSUE TITLE
Featured themes section is not aligned with the rest of page in Themes homepage

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2076]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/themes/
2.Observe the page layout

Expected results:
All sections are correctly aligned 

Actual results:
Featured themes section is not alligned with the rest of page(it is not aligned with Top Rated section in the right side of the page)

Please see screencast for this bug : http://screencast.com/t/Jsj310AVr

**Comment by tofumatt** [comment]
This was fixed in #2029 but is not on stage yet.

**Comment by vcarciu** [comment]
Verified as fixed :

**Comment by vcarciu** [comment]
Featured themes section is still not 100% alligned with the rest of page : http://screencast.com/t/YsegZIEUYW

**Comment by tofumatt** [comment]
I am seeing the alignment issues here, but not the hover effect breaking the layout. Can someone confirm only the alignment issues are still present and not the breakage in the screencast?

**Comment by muffinresearch** [comment]
This is the issue remaining.

![Uploading Themes____Add-ons_for_Firefox.png…]()

**Comment by vcarciu** [comment]
Verified as fixed : 
![themesalign](https://cloud.githubusercontent.com/assets/1583842/14673011/01c60b8a-0704-11e6-859e-907646591151.png)
