### ISSUE TITLE
background breaks if window is smaller than page

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-server#2152]
![amo-blue-bg-breaks-scroll](https://cloud.githubusercontent.com/assets/8145891/14214245/fd881616-f809-11e5-8dbe-f5e3306e24b7.gif)
the blue background should still stretch the full width of the page.

**Comment by ValentinaPC** [comment]
This was also reproducing before style refresh. 
Please see: #1509

**Comment by ValentinaPC** [comment]
Verified as fixed on AMo-dev FF45(Win 7)
Postfix screenshot: 
![2016-04-05_1046](https://cloud.githubusercontent.com/assets/15685960/14274837/6db1811a-fb1c-11e5-935a-0f6046ad8387.png)

**Comment by designakt** [comment]
This does not look fixed to me. I currently get a horizontal scroll-bar even if the window is wide enough, and a white stripe to the right on smaller windows.
![amo-bg-behaviour](https://cloud.githubusercontent.com/assets/8145891/14284238/ef6db384-fb46-11e5-8829-49338180a58f.gif)
 
In the initial restyle the background has been solved with a min-width: 1018px; on the body which results in the following. Which is good as it preserves some spacing left and right of the content and makes sure the blue always stretches all the way.
![amo-bg-behaviour-desired](https://cloud.githubusercontent.com/assets/8145891/14284253/08a9f362-fb47-11e5-8f63-4e4654b8c57d.gif)

observed in Firefox Release on Windows 10.

**Comment by ValentinaPC** [comment]
I've missed a place where this issue is still reproducing. :(
Please see the screenshot: 
![2016-04-08_1211](https://cloud.githubusercontent.com/assets/15685960/14379535/15d087ac-fd83-11e5-9c85-e2d9d8c77ca3.png)

**Comment by tofumatt** [comment]
@ValentinaPC Can you include the URL and/or steps to reproduce when re-opening the bug please? I don't know which page that is and how to get it to show :smile:

**Comment by ValentinaPC** [comment]
:)
Steps to reproduce:
1. Sign in to AMO-dev page
2. Go to details page for an add-on with public stats (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular)
3. Click on the users link to load statistics page https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/statistics/?last=30
4. Resize the browser

**Comment by designakt** [comment]
I found another odd behavior that shows if one views the site in Firefox "Responsive Design Mode":
The background stops a view px before the edge of the window:
![screen shot 2016-04-11 at 14 57 21](https://cloud.githubusercontent.com/assets/8145891/14427598/dd7bfa60-fff5-11e5-83e9-22ccbdd28c54.png)
(Seen on https://addons.mozilla.org in Firefox Nightly on Windows 10)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF45(Win 7) and encountered the next results:
1. On homepage using "Responsive Design Mode" - fixed:
![addons](https://cloud.githubusercontent.com/assets/15685960/14489691/47226e68-0177-11e6-93d6-f46ee2419947.png)
2. On Statistics Dashboard using "Responsive Design Mode" - not fixed:
![responsive](https://cloud.githubusercontent.com/assets/15685960/14489719/6f246056-0177-11e6-8c1f-47d84ec133d6.png)
3. On Statistics Dashboard browser resize - header fixed:
![header](https://cloud.githubusercontent.com/assets/15685960/14489740/8b49a41c-0177-11e6-8f97-20ad2bf66799.png)
4. On Statistics Dashboard browser resize - footer not fixed:
![footer](https://cloud.githubusercontent.com/assets/15685960/14489750/9a26e6ca-0177-11e6-80ad-f8ae60b78a31.png)

Reopening.

**Comment by tofumatt** [comment]
I think the footer is a separate bug (I hadn't seen that before), I'll fix it here but in the future it would be better to file something new :smile:

**Comment by ValentinaPC** [comment]
I'll always lived under the impression that compact is better :smile:

**Comment by ValentinaPC** [comment]
@tofumatt : and the issue commented by designakt (about using responsive design mode) that is reproducing on Stats page...should be fixed or log another issue? :smile:

**Comment by tofumatt** [comment]
That should be fixed.

**Comment by ValentinaPC** [comment]
@tofumatt : "the issue commented by designakt (about using responsive design mode) that is reproducing on Stats page" - this is not fixed (don;t know how important is to be fixed): 
![header](https://cloud.githubusercontent.com/assets/15685960/14498481/48b47006-01a3-11e6-8088-c8809b8e4980.png)

The footer issue is fixed on AMO-dev FF45(Win 7).
Postfix screenshot: 
![footer](https://cloud.githubusercontent.com/assets/15685960/14498527/81191b04-01a3-11e6-865c-3ec70cb09900.png)

**Comment by tofumatt** [comment]
If it can’t be reproduced outside responsive design mode (or really even in) it’s not a blocker.

A separate issue for that would be good; it’s likely a good first bug.
