### ISSUE TITLE
Display issues for navigation arrows in other languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-server#2268]
Steps to reproduce:
1. Load AMO-prod page https://addons.mozilla.org/en-US/firefox/
2. Click "See all" from Featured Extensions section https://addons.mozilla.org/en-US/firefox/extensions/?sort=featured
3. Change the language to French
4. Observe the navigation arrows

Expected results:
There are no display or layout issues.

Actual results:
The nav arrows appear on 2 rows.

Notes/Issues:
Reproducible in all pages that have navigation arrows. Reproducible for other languages too.
Verified on FF45(Win 7). Issue is reproducing on AMO-prod, dev and stage.
Screenshot for this issue: 
![2016-04-08_0939](https://cloud.githubusercontent.com/assets/15685960/14376672/93d4149e-fd73-11e5-8810-ee8513770262.png)

**Comment by diox** [comment]
I can't reproduce in prod. I tested in English, French and German.
![screen shot 2016-05-02 at 11 35 10](https://cloud.githubusercontent.com/assets/187006/14951547/10116e14-105a-11e6-956f-6726f39f6383.png)

**Comment by diox** [comment]
It has probably been fixed by a recent change since it was opened 2 weeks ago. Please re-open if I'm wrong.

**Comment by ValentinaPC** [comment]
Was partially fixed. There are still some languages for which this is reproducing. 
Maybe there is a easy way to fix this for all lang.

Please see the screenshot:
![g](https://cloud.githubusercontent.com/assets/15685960/14977285/6162b748-111b-11e6-82fa-d3cd9801cab8.png)
 
Examples:
https://addons.mozilla.org/uk/firefox/extensions/?sort=featured
https://addons.mozilla.org/ru/firefox/extensions/?sort=featured
https://addons.mozilla.org/el/firefox/extensions/?sort=featured
https://addons.mozilla.org/bg/firefox/extensions/?sort=featured

**Comment by andymckay-limited-access** [comment]
This is a dupe of #2007.

**Comment by ValentinaPC** [comment]
@andymckay-limited-access : I am not talking about arrows with different sizes in this issue, but about arrows on two rows when using some languages that make the navigation buttons bigger then expected. 
Also, that is fixed, this is not.
Feel free to close it if you think does not worth fixing it.
Thanks.

**Comment by diox** [comment]
@tofumatt is that something you could look at ? You're more familiar with the CSS than I am.

**Comment by tofumatt** [comment]
@diox Sure thing 👍🏻

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF46(Win 7).
Postfix screenshots: 
![bg](https://cloud.githubusercontent.com/assets/15685960/15313579/e2285eb0-1c14-11e6-9519-3cfec877e913.png)
![el](https://cloud.githubusercontent.com/assets/15685960/15313580/e228f0c8-1c14-11e6-8c6d-51a2d0323137.png)
![ru_001](https://cloud.githubusercontent.com/assets/15685960/15313582/e22a0288-1c14-11e6-8bf9-43e9d1d4201c.png)
![uk_001](https://cloud.githubusercontent.com/assets/15685960/15313581/e229dd3a-1c14-11e6-9496-173ce71ba490.png)
