### ISSUE TITLE
Reduce the header size on landing page

### ISSUE THREAD

**Issue by Archaeopteryx** [mozilla/addons-server#2277]
Visiting addons.mozilla.org for the first time shows a header including the pick of the month which is 600 physical pixel high (480px virtual because 1.25 pixel density here). After a reload, it's still 500/400 px because the notice what add-ons can do is gone.

Ideas to decrease the header's size:
- Move the Firefox logo and the 'Add-ons' label to the top (left of register and sign in)
- Reduce spacing between 'Add-ons' block and pick of the month and pick of the month and main content.
- Put pick of the month in a box (without style like shouting?) and put it left of the pick of the months title.

**Comment by andymckay** [comment]
I can't reproduce this, has this been fixed with all the other changes?

**Comment by Archaeopteryx** [comment]
Still reproduces on prod and addons-dev: ![screenshot](https://cloud.githubusercontent.com/assets/216576/14502592/3a0b6466-01ac-11e6-9433-998728f89984.png)

**Comment by andymckay** [comment]
I get the tall header because of the message. But once I revisit, its back to expected size.

**Comment by muffinresearch** [comment]
If I understand correctly I think this bug is more about the OP saying the re-designed carousel is making the header too large compared to what it used to be. Since the old site had the carousel more in-line to one side under the header.

That said it's implemented as designed so it's not a bug per se.

**Comment by eviljeff** [comment]
not a bug and we're going to rewrite everything in addons-frontend anyway
