### ISSUE TITLE
"Add" button is missing from Featured Themes in homepage

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-server#2375]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0

Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/
2.Hover over Featured themes

Expected results:
"Add" button is displayed when hovering over themes

Actual results:
"Add" button is missing

Please see screencast for this bug : http://screencast.com/t/6yXwLEVzJ9

**Comment by andymckay-limited-access** [comment]
This is now fixed.

**Comment by vcarciu** [comment]
The issue is still reproducible on -dev : 
![themes](https://cloud.githubusercontent.com/assets/1583842/14703923/0aaddff4-07bb-11e6-8bef-13318b41a545.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![featthemes](https://cloud.githubusercontent.com/assets/1583842/14789400/fabb9f70-0b14-11e6-936b-80b2ced97df2.gif)
