### ISSUE TITLE
Add-ons and themes approval is not working

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#2640]
**Steps to reproduce:**
1. Open editor tools: https://addons.allizom.org/en-US/editors/
2. Select any add-on or theme and try to approve it.

**Expected results:**
add-ons and themes can be approved.

**Actual results:**
add-ons and themes can't be approved. "Oops! We had an error." 500 error is displayed

**Notes/Issues:**
Verified in FF46(Win7) Issue can be reproduced in amo-stage (not reproducing in amo-dev)
This issue was not reproducing yesterday
Screenshot for this issue:
![error](https://cloud.githubusercontent.com/assets/15685441/15214335/107ca4b0-1855-11e6-968d-8ab922d14e0a.png)

**Comment by diox** [comment]
@jasonthomas do you know why this traceback is happening ? https://sentry.prod.mozaws.net/operations/olympia-stage/issues/331213/

**Comment by jasonthomas** [comment]
Yes, there was a issue with the SSL certificate configured on the stage HSM. This should now be fixed.

**Comment by madalincm** [comment]
This is still reproducing for existing themes: http://screencast.com/t/PAOcQBYWy
New submitted themes can be approved, old ones can't.

**Comment by diox** [comment]
https://sentry.prod.mozaws.net/operations/olympia-stage/issues/247929/

**Comment by diox** [comment]
Closing, it's because this theme author was deleted. It sucks and we should fix it, but it's a different issue, that does not block today's release (not a new regression) so let's file it separately.

**Comment by madalincm** [comment]
Marking this one as verified fixed and I will file a new bug for the other issue.
