### ISSUE TITLE
A legacy add-on version can be uploaded as a new version for a webextension for some specific version number

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-server#3670]
### Steps to reproduce:
1. Open amo-dev and submit a listed webextension that has the version number "1"
2. Open the edit listing page for the webextension uploaded in step 1 and and click the Upload new Version
3. Upload a legacy add-on that has the version number "1.0"
### Expected Results:

An warning id displayed, an add-on can't be uploaded over a webextension
### Actual Results:

The add-on can be uploaded
### Notes/Issues:

Verified in FF49,(Win7) Issue can be reproduced in amo-dev
Link for the add-on used in test https://addons-dev.allizom.org/en-US/developers/addon/testaddonoverwebext01/edit

 version 1 is a webextension: https://addons-dev.allizom.org/en-US/developers/addon/testaddonoverwebext01/versions/1529841

version 1.0 is a legacy add-on: https://addons-dev.allizom.org/en-US/developers/addon/testaddonoverwebext01/versions/1529842

**Comment by EnTeQuAk** [comment]
Hmm, this should have been fixed by https://github.com/mozilla/addons-server/pull/3669 - I'll take a look.

**Comment by EnTeQuAk** [comment]
actually, is this still reproducable?

**Comment by ValentinaPC** [comment]
This is still reproducible. 
Tried on AMO-dev FF49.0.2(Win 7) not only for some versions, but for all (tried with 1.0 or 2)
Used webextension: https://addons-dev.allizom.org/en-US/developers/addon/clear-stage-dev/versions/1530106 - new add-on version was uploaded without any warning.

**Comment by EnTeQuAk** [comment]
Okay, so the problem here is that on AMO we compare by exact version numbers to find existing versions with the same version number. According to https://developer.mozilla.org/en-US/docs/Toolkit_version_format `2` and `2.0` should be identical but we don't find `2.0` as an existing version to `2` if you're submitting that kind of combination.

I believe it's an edge-case and might need some thinking since we cannot simply use `version_int` since there were some problems in the past with beta/alpha/whatever versions.

Maybe adding @jvillalobos for additional input whether this is worth doing

**Comment by jvillalobos** [comment]
Submitting version numbers that are essentially duplicate will cause problems with auto-updates and possibly other things, so our duplicate detection should match what Firefox does. Having said that, it's a minor edge case that we shouldn't be too concerned about IMO.

**Comment by EnTeQuAk** [comment]
Given that we simply don't accept legacy add-ons anymore I'm going to close this.
