### ISSUE TITLE
Permissions out of sync

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-server#7265]
### Describe the problem and steps to reproduce it:

This is an add-on that has every permission.

https://addons.mozilla.org/en-US/firefox/addon/every-event/

### What happened?

The permissions seem out of sync with Firefox.

### What did you expect to happen?

They were insync.

### Anything else we should know?

I know this isn't on the new site yet, but I imagine this is a back end code problem. Either we haven't got the strings in for all the permissions, or the permissions entry isn't being updated as we update the addon. I suspect the former.

![screenshot 2018-01-11 13 41 23](https://user-images.githubusercontent.com/74699/34849150-3e705afe-f6d6-11e7-89a2-548fe5be31f2.png)

![screenshot 2018-01-11 13 42 13](https://user-images.githubusercontent.com/74699/34849152-40ddd78a-f6d6-11e7-9f68-76fe2b478f56.png)

cc @eviljeff

**Comment by eviljeff** [comment]
fixed for now by @bqbn and logged https://bugzilla.mozilla.org/show_bug.cgi?id=1430621 to run automatically on each deployment.

**Comment by AlexandraMoga** [comment]
Verified this on all AMO-servers and here is what I observed:

PROD and -DEV - one permission is still missing
![image](https://user-images.githubusercontent.com/31961530/34989988-22e64c4e-facd-11e7-9fe4-1ef898cc6ef9.png)

STAGE is still displaying the old permission list -maybe not deployed yet?

**Comment by eviljeff** [comment]
stage is now synced too.

The missing permission will need more investigation - `downloads.open` is the first `.` permission the code wasn't tested with permission names in that format.

**Comment by eviljeff** [comment]
okay, the problem _wasn't_ `downloads.open` but an extra manifest key, `devtools_page` [[MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/devtools_page)] that Firefox now treats as a permission and displays in the popup.

Filed https://github.com/mozilla/addons-server/issues/7316 for the follow-up now the permissions themselves are in sync.

**Comment by AlexandraMoga** [comment]
Waiting for [#7316](https://github.com/mozilla/addons-server/issues/7316) to land before marking this as verified fixed

**Comment by eviljeff** [comment]
As you wish, though it might be a while as it's a new feature rather than a fix.

**Comment by AlexandraMoga** [comment]
If  [#7316](https://github.com/mozilla/addons-server/issues/7316) will not land within this milestone, I suppose we can mark this as verified fixed
