### ISSUE TITLE
addon_count for collections is not accurate

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-server#8065]
The `addon_count` returned for a collection from the `collections` API is the number of add-ons that have been added to the collection, but some of those may have subsequently removed/deleted from the site, so it is no longer the true number of add-ons in the collection, from the perspective of a user.

This is causing issues on the frontend both in terms of the number of add-ons reported for a collection on the collection details page (https://github.com/mozilla/addons-frontend/issues/4789) and also, I believe, in terms of messing with our paging logic.

**Comment by bobsilverberg** [comment]
There seems to be more weirdness that just removed add-ons. In this example: https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-search-engines/, the collection detail page states that the collection holds 8 add-ons, but 10 are displayed, and if you edit the collection there are 11 in it. The difference between the 10 and 11 could be explained by a deleted/removed add-on, but I'm not sure why `addon_count` would be *less* than the actual number of add-ons in the collection.

**Comment by eviljeff** [comment]
`addon_count` is value that gets calculated in a task - supposedly after every modification to the collection, so if it's not the same as add-ons you can see in collection edit then something isn't working, I guess.  The count doesn't exclude based on status so, yeah, it wouldn't include disabled/deleted add-ons too.   (Also, I can't see it's called when the add-on's status changes either)

**Comment by eviljeff** [comment]
Fwiw, we don't list collections publicly in new frontend, so we could drop it (or stop pre-calculating it at least).  @bobsilverberg is there anywhere we show this value outside of the the collection page itself?

**Comment by diox** [comment]
See https://github.com/mozilla/addons-server/issues/6629 regarding the task being broken

**Comment by eviljeff** [comment]
> See #6629 regarding the task being broken

the more reason to just drop the value from the API response and remove it entirely with legacy collection pages :)

**Comment by bobsilverberg** [comment]
I have yet to look into it fully, but I think we need it for pagination, even if we do not want to display the number of add-ons in the collection on the details page (although I think we still want to do that as well). Is calculating it on the fly before sending the API response a possibility, rather than storing it?

**Comment by eviljeff** [comment]
It's certainly possible, though it's an extra db query per collection, which could get expensive if it were to be included in the list response for a user with many collections.  

If it were limited to detail responses then it's acceptable; if it was only needed when the add-ons were included too (i.e. http://addons-server.readthedocs.io/en/latest/topics/api/collections.html#get--api-v3-accounts-account-(int-user_id|string-username)-collections-(int-id|string-collection_slug)-?with_addons) then we get the addon_count for free anyway.

**Comment by AlexandraMoga** [comment]
This is even more visible now that legacy add-on files have been disabled.
Here is another example, just for the record:

- on the frontend 
![image](https://user-images.githubusercontent.com/31961530/46872831-e4b20900-ce3d-11e8-8401-f90f2ccd2387.png)

- api response for this collection:

https://addons-dev.allizom.org/api/v4/accounts/account/mozilla/collections/ad-blockers/?with_addons

**Comment by eviljeff** [comment]
@bobsilverberg can we just drop this for the collection view?  We'll return it only when collection addons are requested for pagination.

**Comment by bobsilverberg** [comment]
Sorry to take so long to get back to you, @eviljeff. I wanted to take a close look at the code. I actually figured out a way to fix this so that we don't need an accurate `addon_count` from the collection details API, so I'm going to close this, and submit a patch that will fix https://github.com/mozilla/addons-frontend/issues/4789, as well as any other issues that have been opened about collection counts.

**Comment by bobsilverberg** [comment]
Actually, there is one place where we're currently displaying a collection count where we're not also retrieving the list of add-ons in the collection, which is the page listing users' collections:

![screenshot 2018-10-18 13 39 30](https://user-images.githubusercontent.com/142755/47173177-62ad5e80-d2db-11e8-886c-e29a4be31310.png)

If we do not fix this bug we'll either have to remove the count of add-ons for each collection from that page, or we'll have to continue showing an incorrect count.

@jvillalobos What do you think we need to do about this?

**Comment by jvillalobos** [comment]
I think keeping the count in that view is useful, even if it can be inaccurate. And it will be presumably fixed in https://github.com/mozilla/addons-server/issues/6629, right?

**Comment by diox** [comment]
Duplicate of #6629 (which may be working at the moment?)

**Comment by AlexandraMoga** [comment]
The issue mentioned in https://github.com/mozilla/addons-server/issues/8065#issuecomment-431099034 is still happening on -dev, so I do not think that this is fixed yet:

- Count on collections list page vs count on collection details page
![image](https://user-images.githubusercontent.com/31961530/55138885-29580500-513d-11e9-9616-b181dc485d6c.png)

**Comment by diox** [comment]
Re-opening because it may be a different problem than #6629 after all
